# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "alsa_midi"
  s.version = "0.9.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brent Sanders"]
  s.date = "2011-09-15"
  s.description = "ALSA bindings for the MIDI Sequencer"
  s.email = "git@thoughtnoise.net"
  s.extensions = ["ext/extconf.rb", "ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "alsa_midi.gemspec",
    "ext/extconf.rb",
    "ext/src/alsa_midi_seq.c",
    "ext/src/alsa_midi_seq.h",
    "ext/src/client.c",
    "ext/src/client.h",
    "ext/src/ev.c",
    "ext/src/ev.h",
    "ext/src/fifo.c",
    "ext/src/fifo.h",
    "ext/src/looper.c",
    "ext/src/looper.h",
    "ext/src/pat.c",
    "ext/src/pat.h",
    "ext/src/port.c",
    "ext/src/port.h",
    "ext/src/scale.c",
    "ext/src/scale.h",
    "lib/alsa_midi.rb",
    "lib/alsa_midi/client.rb",
    "lib/alsa_midi/error.rb",
    "lib/alsa_midi/event.rb",
    "lib/alsa_midi/looper.rb",
    "lib/alsa_midi/pattern.rb",
    "lib/alsa_midi/port.rb",
    "lib/alsa_midi/scale.rb",
    "send_ev.rb",
    "test/helper.rb",
    "test/test_alsa_midi_looper.rb",
    "vkbd_octave.rb"
  ]
  s.homepage = "http://git.thoughtnoise.net/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "ALSA MIDI-SEQ bindings"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<color_debug_messages>, [">= 1.1.3"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<color_debug_messages>, [">= 1.1.3"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<color_debug_messages>, [">= 1.1.3"])
  end
end

